name: Deploy to InfinityFree

on:
  push:
    branches:
      - main   # Branch, który chcesz publikować

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Pobranie repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Wgranie na FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6

        with:
          server: ftpu.infinityfree.net          # Twój FTP host
          username: ${{ secrets.FTP_USERNAME }}  # Secret z GitHub
          password: ${{ secrets.FTP_PASSWORD }}  # Secret z GitHub
          local-dir: ./                           # Katalog z plikami do wysłania
          server-dir: /htdocs/                      # Katalog na serwerze
